eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082

spring:
  datasource:
    schema: classpath*:/schema.sql
    data: classpath*:/import.sql
  jpa:
    show_spl: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true